name: Update Custom Configuration

on:
  workflow_dispatch:
    inputs:
      api_server:
        description: '自定义服务器地址'
        required: true
        default: '111.46.161.134'
      rs_pub_key:
        description: '服务器公钥'
        required: true
        default: 'xgtv1234'
      password:
        description: '固定连接密码'
        required: true
        default: 'aa000000'
      version_tag:
        description: '版本标签 (如: 1.3.9)'
        required: true
        default: '1.3.9'

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Verify and update .gitmodules
        run: |
          # 确保 .gitmodules 文件指向正确的 fork 仓库
          GIT_USER="${{ github.repository_owner }}"
          sed -i "s|url = https://github.com/rustdesk/hbb_common|url = https://github.com/$GIT_USER/hbb_common|g" .gitmodules
          cat .gitmodules
          
          # 提交 .gitmodules 文件更改
          git add .gitmodules
          git commit -m "Update .gitmodules to point to forked hbb_common"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Update hbb_common config
        run: |
          # 更新子模块
          git submodule init
          git submodule sync
          git submodule update --init --recursive
          
          cd hbb_common
          # 备份原文件
          cp src/config.rs src/config.rs.bak
          
          # 更新配置
          sed -i 's/pub const RENDEZVOUS_SERVERS: \&\[\&str\] = \&\["[^"]*"\]/pub const RENDEZVOUS_SERVERS: \&\[\&str\] = \&\["${{ github.event.inputs.api_server }}"\]/' src/config.rs
          sed -i 's/pub const RS_PUB_KEY: \&str = "[^"]*"/pub const RS_PUB_KEY: \&str = "${{ github.event.inputs.rs_pub_key }}"/' src/config.rs
          
          # 查找并更新固定密码 - 改进正则表达式以更准确地匹配
          if grep -q "map\.insert(\"password\"\.to_string(), \"[^\"]*\")" src/config.rs; then
            sed -i 's/map\.insert("password"\.to_string(), "[^"]*")/map\.insert("password"\.to_string(), "${{ github.event.inputs.password }}")/' src/config.rs
          else
            echo "无法找到密码设置行，请手动检查 src/config.rs 文件"
            exit 1
          fi
          
          # 检查更改是否成功
          grep -n "RENDEZVOUS_SERVERS" src/config.rs
          grep -n "RS_PUB_KEY" src/config.rs
          grep -n "password" src/config.rs
          
          # 提交更改
          git add src/config.rs
          git commit -m "Update custom configuration settings"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/hbb_common.git HEAD:main
          
          # 获取当前 commit ID
          COMMIT_ID=$(git rev-parse HEAD)
          echo "hbb_common updated to commit: $COMMIT_ID"
          cd ..

      - name: Update API server in main repository
        run: |
          # 更新 src/common.rs 中的 API 服务器地址
          if grep -q "format!(\"http://{}:{}\", \"[^\"]*\"" src/common.rs; then
            sed -i 's/format!("http:\/\/{}:{}", "[^"]*"/format!("http:\/\/{}:{}", "${{ github.event.inputs.api_server }}"/' src/common.rs
          else
            echo "无法找到 API 服务器设置行，请手动检查 src/common.rs 文件"
            cat src/common.rs | grep -A 5 -B 5 "format!(\"http"
            exit 1
          fi
          
          # 检查更改是否成功
          grep -n "format!(\"http" src/common.rs
          
          # 更新子模块引用
          git submodule update --remote --merge
          
          # 提交更改
          git add src/common.rs hbb_common
          git commit -m "Update API server and hbb_common reference"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Create and push version tag
        run: |
          git tag -a ${{ github.event.inputs.version_tag }} -m "Release ${{ github.event.inputs.version_tag }} with custom configuration"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.event.inputs.version_tag }}
          
      - name: Verification
        run: |
          echo "============== 验证配置 =============="
          echo "检查 .gitmodules 文件："
          cat .gitmodules
          
          echo "检查 hbb_common 配置："
          cat hbb_common/src/config.rs | grep -A 1 -B 1 "RENDEZVOUS_SERVERS"
          cat hbb_common/src/config.rs | grep -A 1 -B 1 "RS_PUB_KEY"
          cat hbb_common/src/config.rs | grep -A 1 -B 1 "password"
          
          echo "检查 API 服务器配置："
          cat src/common.rs | grep -A 2 -B 2 "format!(\"http"
          
          echo "检查子模块 commit ID："
          cd hbb_common && git rev-parse HEAD

  trigger-flutter-build:
    needs: update-config
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: ${{ github.event.inputs.version_tag }}
    secrets: inherit 